# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MiniChallengeIV' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MiniChallengeIV
  pod 'Charts'
  pod 'LayoutHelper'

  target 'MiniChallengeIVTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MiniChallengeIVUITests' do
    # Pods for testing
  end

end
